# ============================================================
#  L'ANNUAIRE DES APPLICATIONS (gere par les OPS)
#  Chaque hote du groupe [apps] devient AUTOMATIQUEMENT une route :
#      app1 -> http://localhost:8088/app1
#  Ajouter une application = ajouter UNE LIGNE ici, puis rejouer site.yml.
# ============================================================
[apps]
app1 ansible_connection=community.docker.docker
app2 ansible_connection=community.docker.docker

# Le proxy que les ops administrent
[proxy]
proxy ansible_connection=community.docker.docker
