---
- name: Monter les conteneurs avec Ansible
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Démarrer la stack (docker compose)
      community.docker.docker_compose_v2:
        project_src: .
        state: present

    - name: Générer l'inventaire pour la suite
      ansible.builtin.copy:
        dest: inventory.ini
        content: |
          [wordpress]
          wp ansible_connection=community.docker.docker
          [db]
          db ansible_connection=community.docker.docker
